export const mockCrops = [
  { id: 1, name: 'Wheat', basePrice: 2200 },
  { id: 2, name: 'Paddy', basePrice: 2300 },
  { id: 3, name: 'Maize', basePrice: 2100 },
  { id: 4, name: 'Mustard', basePrice: 5650 },
  { id: 5, name: 'Chickpea', basePrice: 5440 },
];

export const mockBuyers = [
  {
    id: 1,
    name: 'Sharma Grain Traders',
    type: 'Wholesaler',
    cropRequired: 'Wheat',
    pricePerQtl: 2280,
    distance: 12,
    quantityNeeded: 180,
    contact: '+91 98765 43210',
  },
  {
    id: 2,
    name: 'Fresh Basket Market',
    type: 'Retailer',
    cropRequired: 'Paddy',
    pricePerQtl: 2380,
    distance: 8,
    quantityNeeded: 95,
    contact: '+91 98765 43211',
  },
  {
    id: 3,
    name: 'Kisan Agro Foods',
    type: 'Wholesaler',
    cropRequired: 'Maize',
    pricePerQtl: 2175,
    distance: 22,
    quantityNeeded: 250,
    contact: '+91 98765 43212',
  },
  {
    id: 4,
    name: 'Green Leaf Stores',
    type: 'Retailer',
    cropRequired: 'Mustard',
    pricePerQtl: 5850,
    distance: 15,
    quantityNeeded: 60,
    contact: '+91 98765 43213',
  },
  {
    id: 5,
    name: 'Bharat Pulses Depot',
    type: 'Wholesaler',
    cropRequired: 'Chickpea',
    pricePerQtl: 5580,
    distance: 18,
    quantityNeeded: 140,
    contact: '+91 98765 43214',
  },
];

export const mockPriceHistory = [
  {
    cropId: 1,
    mandi: 'Karnal Mandi',
    wholesale: 2260,
    retail: 2940,
    msp: 2200,
    date: '2026-08-01',
  },
  {
    cropId: 2,
    mandi: 'Ludhiana Mandi',
    wholesale: 2350,
    retail: 3100,
    msp: 2300,
    date: '2026-08-03',
  },
  {
    cropId: 3,
    mandi: 'Indore Mandi',
    wholesale: 2140,
    retail: 2780,
    msp: 2100,
    date: '2026-08-05',
  },
  {
    cropId: 4,
    mandi: 'Jaipur Mandi',
    wholesale: 5780,
    retail: 6950,
    msp: 5650,
    date: '2026-08-07',
  },
  {
    cropId: 5,
    mandi: 'Bhopal Mandi',
    wholesale: 5520,
    retail: 6700,
    msp: 5440,
    date: '2026-08-10',
  },
];

export const mockSupplyChain = [
  {
    cropId: 1,
    farmerCost: 1850,
    wholesalerCost: 2260,
    distributorCost: 2490,
    retailerCost: 2700,
    consumerPrice: 2940,
    transportCost: 120,
    distance: 35,
  },
  {
    cropId: 2,
    farmerCost: 1950,
    wholesalerCost: 2350,
    distributorCost: 2620,
    retailerCost: 2880,
    consumerPrice: 3100,
    transportCost: 135,
    distance: 42,
  },
  {
    cropId: 3,
    farmerCost: 1720,
    wholesalerCost: 2140,
    distributorCost: 2370,
    retailerCost: 2550,
    consumerPrice: 2780,
    transportCost: 105,
    distance: 28,
  },
  {
    cropId: 4,
    farmerCost: 4900,
    wholesalerCost: 5780,
    distributorCost: 6200,
    retailerCost: 6550,
    consumerPrice: 6950,
    transportCost: 180,
    distance: 50,
  },
  {
    cropId: 5,
    farmerCost: 4680,
    wholesalerCost: 5520,
    distributorCost: 5900,
    retailerCost: 6300,
    consumerPrice: 6700,
    transportCost: 150,
    distance: 40,
  },
];

export const mockGovernmentUpdates = [
  {
    id: 1,
    category: 'Market notice',
    title: 'Mandi Holiday Alerts',
    description: 'Patiala Mandi will remain closed on 15 August for Independence Day. Plan produce deliveries for the next working day.',
    icon: '📢',
  },
  {
    id: 2,
    category: 'Local support',
    title: 'Block Officer Contact',
    description: 'For crop advisories and field support, contact the Patiala Block Agriculture Office on working days between 9 AM and 5 PM.',
    icon: '☎️',
  },
  {
    id: 3,
    category: 'Scheme update',
    title: 'Active Government Schemes',
    description: 'Applications are open for PM-KISAN support, crop insurance, and farm mechanisation assistance. Check eligibility before applying.',
    icon: '🏛️',
  },
];
